language: java

jdk:
- openjdk14

sudo: true

script: mvn clean install

deploy:
  provider: releases
  skip_cleanup: true

  on:
    tags: true
    all_branches: true
    repo: hakdogan/IntroduceToEclicpseVert.x